name: Auto-Pack

on:
  push:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Download Code
        uses: actions/check${{ steps.commit.outputs.short }}@v2
        with:
          persist-credentials: false
      - name: Dependces
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
          pip3 install -r requirements.txt
      - name: Pack
        run: |
          mkdir ${{ steps.commit.outputs.short }}
          pyinstaller -F hexo.py
          mv dist/* ${{ steps.commit.outputs.short }}/
          mv README.md ${{ steps.commit.outputs.short }}/
          mv LICENSE ${{ steps.commit.outputs.short }}/
          zip -r ${{ steps.commit.outputs.short }}.zip ${{ steps.commit.outputs.short }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.commit.outputs.short }}
          path: ${{ steps.commit.outputs.short }}
      - name: Create Pre-release And Upload Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.commit.outputs.short }}.zip
          file_glob: true
          tag: ${{ steps.commit.outputs.short }}
          overwrite: true
          release_name: ${{ steps.commit.outputs.short }}
          body: |
            来自commit ${{ steps.commit.outputs.short }}的自动打包
          prerelease: true